### PR TITLE
releasing: add information about a quick way for making forum topics

### PR DESCRIPTION
**Pull request by HybridDog**
M  chapters/releasing.md

### CODE REVIEW

**Comment by rubenwardy** [comment]
I'm hesitant to advise readers to download a shell script outside of my control. 

If this just generates the bbcode, would it not be better as a Html form and javascript

**Comment by HybridDog** [comment]
>I'm hesitant to advise readers to download a shell script outside of my control.

You can edit it and put it into this repository.

>If this just generates the bbcode, would it not be better as a Html form and javascript 

yes, this would be better,
maybe it's possible to make a greasemonkey script which makes it possible to generate the code at minetest forums

**Comment by DraggonFantasy** [comment]
+ HTML form and javascript is a cross-platform way, when .sh script wouldn't work under Windows, for example.

**Comment by rubenwardy** [comment]
74086b4

**Pull request closed without merging**
